public with sharing class OpportunityHandler implements ITrigger {
	public OpportunityHandler() {
		
	}
		public void bulkBefore(){

	}

	public void bulkAfter(){

    }
         
    public void beforeInsert(SObject so){

    }
     
    public void beforeUpdate(SObject oldSo, SObject so){

    }

    public void beforeDelete(SObject so){

    }

    public void afterInsert(SObject so){

    }

    public void afterUpdate(SObject oldSo, SObject so){

    }

    public void afterDelete(SObject so){

    }

    public void andFinally(){
    	
    }
}